### ISSUE TITLE
Leaked FileInputStream

### ISSUE THREAD

**Issue by hmijail** [ConsenSys/IPFS-Store#39]
https://github.com/ConsenSys/IPFS-Store/blob/987558dffac4fc38751d2e4c5b629902a4f827b8/ipfs-store-client/ipfs-store-client-java/src/main/java/net/consensys/tools/ipfs/ipfsstore/client/java/IPFSStore.java#L81

A FileInputStream is created but never closed.

**Comment by gjeanmart** [comment]
Thanks for this, good catch! It's fixed with PR #40 (release version: 0.1.7)

Feel free to reach out if you have questions or feedback.
