### ISSUE TITLE
Field values are always lower case

### ISSUE THREAD

**Issue by ivohuisjes** [ConsenSys/IPFS-Store#47]
In Pull request PR [#34](https://github.com/ConsenSys/IPFS-Store/pull/34) you added code to ElasticSearchIndexDao.manipulateValue()
`if(value instanceof String) {
return NULL;
} else {
return ((String) value).toLowerCase();
}`

The problem is that **ALL** field values are now lower case. I understand the KEYS should be converted to lowercase, but I would like the VALUES to preserve case.

Is this intended behavior?

**Comment by gjeanmart** [comment]
Thanks for pointing this out. 

This sounds incorrect so I will revert to `return ((String) value);` rather than `return ((String) value).toLowerCase();` and do some tests.

**Comment by gjeanmart** [comment]
Fix in PR #48

**Comment by ivohuisjes** [comment]
you're the best!

**Comment by ivohuisjes** [comment]
I tested the new version (v0.1.14), but the field values (returned after searching with Java API: public Page<Metadata> search(String indexName, Query query, Pageable pageable)) are still returned in lower case.

I started "clean" (removed folders: ipfs-store/ipfs-store-service.elasticsearch-docker/ and ipfs-store/ipfs-store-service.ipfs*, removed containers: docker container prune and rebuild the project from root (ipfs-store): mvn clean package

**Comment by gjeanmart** [comment]
This should be working now. 

Since the latest release (0.1.16), I'm now publishing the Docker images on [DockerHub](https://hub.docker.com/r/gjeanmart/ipfs-store/tags/) so I would recommend to use this.

Moreover, whatever the way you run IPFS-Store, it should print the version in the INFO log when it's started:

> 2018-11-21 19:43:22.134  INFO 12392 --- [           main] n.c.tools.ipfs.ipfsstore.Application     : ############### Application [ipfs-store-service - version: 0.1.16] Started ! ###############
